### ISSUE TITLE
drawing bigger features

### ISSUE THREAD

**Issue by eps696** [Mayukhdeb/torch-dreams#33]
thanks for repo, quite fun and cool!
it seems, the features on example images are drawn bigger, than it happens when using this library. is there any trick for that (besides external upscaling)?

**Comment by Mayukhdeb** [comment]
Hi @eps696, first of all thanks for checking out this project. Glad that you liked it :)

I'm not sure what you mean t when you said "example images". 
I think I'll be able to help you better if you clarify what exactly you meant by that.

**Comment by eps696** [comment]
i meant the images in the `images` folder. but i think i got already - custom transforms (downscaling/cropping) can do that.
here is fullhd test (rendered from CLIP model by OpenAI)
![output](https://user-images.githubusercontent.com/4808408/113028824-6922ae80-9194-11eb-99c3-676b80f460fb.jpg)

**Comment by Mayukhdeb** [comment]
This looks interesting. Did you make this using `torch-dreams` ?

**Comment by eps696** [comment]
yes, `torch-dreams`. the model is from [here](https://github.com/openai/CLIP), neurons can be looked up [here](https://microscope.openai.com/models/contrastive_v2?models.technique=deep_dream)

**Comment by Mayukhdeb** [comment]
Nice! If you plan to make some art with this library, I'd be really grateful if you mention that you made it with torch-dreams.

**Comment by eps696** [comment]
sure! yet for now i'm sticking to the lucid/lucent libraries, as they have quite a few nice tricks, which i'm used to (CPPN export, etc.)
