### ISSUE TITLE
Support for latest pytorch 1.9

### ISSUE THREAD

**Issue by seba-eng** [Mayukhdeb/torch-dreams#48]
according to the requirements.txt, torch>=1.8.0 is required. However the code does not run when the latest version pytorch 1.9 is used. The following line will raise an exception in that case:
https://github.com/Mayukhdeb/torch-dreams/blob/12881f4ec69ef4408d2e03081aec17d7f4fab2b3/torch_dreams/utils.py#L74
If only 1.8.0 works, then the requirements should be updated to that specific version, otherwise the version check in the code should be changed.

**Comment by Mayukhdeb** [comment]
Hi @seba-eng, thank you so much for pointing this out. I'll make the necessary changes and release a new version ASAP.

**Comment by Mayukhdeb** [comment]
Just made a [new release](https://pypi.org/project/torch-dreams/) to add support for torch `v1.9.x`. Thanks for reminding me about this :)

**Comment by seba-eng** [comment]
Thank you for the quick fix!
