### ISSUE TITLE
Colab notebook fails to run: PytorchVersionError

### ISSUE THREAD

**Issue by matthiasgeihs** [Mayukhdeb/torch-dreams#54]
Cell 4 of the Colab notebook [`hello_torch_dreams`](https://colab.research.google.com/github/Mayukhdeb/torch-dreams-notebooks/blob/main/docs_notebooks/hello_torch_dreams.ipynb) fails to run on the current default Colab environment.
The error is:
```
PytorchVersionError: Expected pytorch to have version 1.8.x or higher but got: 2.0.1+cu118
```

**Comment by Mayukhdeb** [comment]
Hi @matthiasgeihs, thanks for pointing out this issue. I will fix it ASAP and roll out a new version.
It might also contain some other interface changes, about which I will inform you after the update has been released.

**Comment by Mayukhdeb** [comment]
Hi @matthiasgeihs. I have fixed the error you were facing.
You can install the latest dev version of torch-dreams with this command:
```
pip install git+https://github.com/Mayukhdeb/torch-dreams
```
Please note that I've also been working on a new upgrade to torch-dreams which involves batched image parameters. Hence there is a small interface change that you have to make on your custom objectives:

![image](https://github.com/Mayukhdeb/torch-dreams/assets/53133634/4b30d8cb-10b5-40b2-ab30-ea0b8bac4749)

I have also updated the [colab notebook](https://colab.research.google.com/github/Mayukhdeb/torch-dreams-notebooks/blob/main/docs_notebooks/hello_torch_dreams.ipynb) to use the dev version for now. So it should run through without any problems.

**Comment by matthiasgeihs** [comment]
Great, thanks for taking a look. Will try that out when I find some time. 🙏

**Comment by matthiasgeihs** [comment]
OK, this works now. 👍 

@Mayukhdeb 
What would be very helpful for someone like me who is not already familiar with the method:
Have some explanations between the commands in the notebook, what exactly is happening there.

I got aware of the project as I was interested in explainable AI, but what I currently see is just some nice looking pictures being produced. I have a very rough idea of what might be happening under the hood, but tbh I don't understand much at the moment. What is the minimal example exactly demonstrating? I think a few high-level comments would really help! 🙂

That being said, the issue seems solved.
