### ISSUE TITLE
confusion about visualizing individual channels

### ISSUE THREAD

**Issue by rmin2000** [Mayukhdeb/torch-dreams#55]
As a freshman in this area, I really appreciate your repo for letting me know how feature visualization works in practice. Thanks!!

In the channel visualization case, the channel index in the example is 119, however, the colab tutorial states the 7th channel in Mixed_6b.branch1x1 is optimized. In my understanding, I think the index of the optimized channel should equal the value of _channel_number_ (119th channel in this case). Or is there something I misunderstood?

**Comment by Mayukhdeb** [comment]
hi @rmin2000 

You are correct. The colab tutorial text has a typo. I am indeed optimizing channel index 119 (another typo there -> it should be `channel_index` and not `channel_number`). I will fix this typo soon. 

Also thank you for your kind words!

**Comment by rmin2000** [comment]
Thank you!
